use_frameworks!

platform :ios, '10.0'

target 'MA_DynamicPointsSlider_Example' do
  pod 'MA_DynamicPointsSlider', :path => '../'

  target 'MA_DynamicPointsSlider_Tests' do
    inherit! :search_paths

    
  end
end
